#!/usr/bin/env bash
#Install nginx on your web-01
#server
#Nginx should be listening on port 80

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw app list
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service restart nginx
