#!/usr/bin/env bash
# iterating from 1 to 10 and displying bad luck in the 4th and good luck in the 8th otherwise Best Scool
i=0
while [ $i -lt 10 ]; do
if [ $i -eq 3 ]; then
echo "bad luck"
elif [ $i -eq 7 ]; then
echo "good luck"
else
echo "Best School"
fi
i=$((i+1))
done
