#!/usr/bin/env bash
# Displays the content of the current directory in a list format
# where only the part of the name after the first dash is displayed.
# Hidden files are not displayed.
for i in *; do
if [[ "$i" == *-* ]]; then
newname=${i#*-}
echo "$newname"
else
echo "$i"
fi
done
